<a href="https://colab.research.google.com/github/Niranjen99/Deep_Learning_Assessment_1/blob/main/MLPDiabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.datasets import load_svmlight_file
import urllib.request
import os

# Download the libsvm data from a URL
#url = 'https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/diabetes_scale'
url = 'https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/diabetes'

data_file = 'data.libsvm'

# Download the data from the URL
urllib.request.urlretrieve(url, data_file)

# Load the libsvm data using scikit-learn
X, y = load_svmlight_file(data_file)

# Convert sparse matrix to a dense NumPy array (if necessary)
X = X.toarray()

print(y)
#change label from -1 to 0 and 1 to 1
y = np.where(y == -1, 0, 1)


# Print shape of the data to confirm
print("Feature matrix shape:", X.shape)
print("Labels shape:", y.shape)
#print(X)
print(y)

[-1.  1. -1.  1. -1.  1. -1.  1. -1. -1.  1. -1.  1. -1. -1. -1. -1. -1.
  1. -1.  1.  1. -1. -1. -1. -1. -1.  1.  1.  1.  1. -1.  1.  1.  1.  1.
  1. -1. -1. -1.  1.  1.  1. -1.  1. -1.  1.  1. -1.  1.  1.  1.  1. -1.
  1.  1. -1.  1.  1.  1.  1. -1.  1.  1. -1.  1. -1.  1.  1.  1. -1.  1.
 -1.  1.  1.  1.  1.  1. -1.  1.  1.  1.  1.  1. -1.  1.  1.  1. -1.  1.
  1.  1.  1. -1.  1.  1.  1.  1.  1. -1. -1.  1.  1.  1.  1.  1.  1.  1.
  1. -1. -1. -1.  1.  1. -1. -1. -1.  1.  1.  1. -1.  1.  1.  1. -1. -1.
  1.  1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1.
  1.  1.  1.  1.  1.  1.  1.  1. -1.  1. -1. -1.  1.  1.  1. -1.  1.  1.
  1.  1. -1. -1.  1.  1.  1.  1. -1. -1.  1.  1.  1. -1.  1. -1.  1. -1.
  1.  1.  1.  1.  1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1. -1.  1. -1.
 -1. -1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1.  1. -1. -1. -1.
 -1.  1. -1. -1. -1. -1.  1.  1.  1.  1.  1. -1.  1.  1. -1. -1.  1.  1.
  1. -1. -1. -1. -1.  1.  1.  1. -1. -1.  1. -1.  1

In [32]:


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler and scale features between -1 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


print(X_train)
# Create a Sequential model
model = Sequential()

# Input layer and first hidden layer with ReLU activation
model.add(Dense(32, input_dim=8, activation='relu'))

# Second hidden layer with ReLU activation
model.add(Dense(16, activation='relu'))

model.add(Dense(8, activation='relu'))



# Output layer with tanh activation since labels  are classifying between -1 and 1
#model.add(Dense(1, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
#model.compile(optimizer=Adam(), loss='mean_squared_error', metrics=['accuracy'])
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

[[0.11764706 0.42211055 0.         ... 0.         0.09649872 0.        ]
 [0.52941176 0.56281407 0.67213115 ... 0.42026828 0.51409052 0.48333333]
 [0.05882353 0.69849246 0.37704918 ... 0.42771985 0.24594364 0.01666667]
 ...
 [0.58823529 0.50753769 0.70491803 ... 0.6795827  0.45175064 0.28333333]
 [0.         0.70854271 0.         ... 0.63189275 0.05422716 0.13333333]
 [0.         0.6281407  0.78688525 ... 0.33532043 0.07856533 0.        ]]


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [34]:
# Train the model
#model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=1)
hist = model.fit(X_train,y_train, epochs =100,validation_data=(X_test, y_test))

# Evaluate the model on training data
train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
print(f"Training Accuracy: {train_accuracy * 100:.2f}%")

# Evaluate the model on test data
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7957 - loss: 0.4193 - val_accuracy: 0.7403 - val_loss: 0.5207
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8022 - loss: 0.3960 - val_accuracy: 0.7468 - val_loss: 0.5182
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8055 - loss: 0.4157 - val_accuracy: 0.7403 - val_loss: 0.5204
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8066 - loss: 0.4096 - val_accuracy: 0.7403 - val_loss: 0.5180
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7926 - loss: 0.4173 - val_accuracy: 0.7403 - val_loss: 0.5123
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8148 - loss: 0.3982 - val_accuracy: 0.7532 - val_loss: 0.5164
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7910 - loss: 0.4292 - val_accuracy: 0.7792 - val_loss: 0.5135
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7984 - loss: 0.4163 - val_accuracy: 0.7662 - v